"""Auto migration 20251203_155157

Revision ID: 1e5cded89d7f
Revises: 8d42c7adf7e2
Create Date: 2025-12-03 15:52:03.096913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5cded89d7f'
down_revision: Union[str, None] = '8d42c7adf7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('example', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
