"""Auto migration 20251203_152235

Revision ID: 1f3a17fc5fc6
Revises: 001_initial
Create Date: 2025-12-03 15:22:42.992098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3a17fc5fc6'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('example', sa.Column('image', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_example_id'), 'example', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_id'), table_name='example')
    op.drop_column('example', 'image')
    # ### end Alembic commands ###
