"""Auto migration 20251203_160836

Revision ID: 6fbb65aad1ec
Revises: 289285f8315f
Create Date: 2025-12-03 16:08:42.153159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbb65aad1ec'
down_revision: Union[str, None] = '289285f8315f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
