"""Auto migration 20251203_152318

Revision ID: 8d42c7adf7e2
Revises: 1f3a17fc5fc6
Create Date: 2025-12-03 15:23:26.074502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d42c7adf7e2'
down_revision: Union[str, None] = '1f3a17fc5fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
