"""Auto migration 20251203_161025

Revision ID: 8f9de85ec2cc
Revises: 6fbb65aad1ec
Create Date: 2025-12-03 16:10:31.728717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9de85ec2cc'
down_revision: Union[str, None] = '6fbb65aad1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
